### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by rolltyed** [MichaelStott/DataframeGUIKivy#1]
Hi!  I am very interested in using your code, but when I run demo.py, I get the following error:

```
Traceback (most recent call last):
   File "/home/mashford/PycharmProjects/DK/demo.py", line 11, in <module>
     from dfguik import DfguiWidget
   File "/home/mashford/PycharmProjects/DK/dfguik.py", line 27, in <module>
     from kivy.garden.matplotlib.backend_kivyagg import FigureCanvas, \
   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 628, in _load_backward_compatible
 KeyError: 'kivy.garden.matplotlib'

Process finished with exit code 1
```

Any ideas on what I can do to correct the error?  I love using Pandas and the ability to display dataframes in Kivy would be awesome.

Thanks!

**Comment by MichaelStott** [comment]
@rolltyed Try installing the matplotlib Kivy garden library.
